### ISSUE TITLE
Make db feature optional

### ISSUE THREAD

**Issue by ohmyarch** [zupzup/woddle#1]

**Comment by zupzup** [comment]
Hey @ohmyarch, could you please add some more description (or really, any ;)) regarding this?

Since this library's purpose is to provide syncing of job runs between several instances, some mechanism for doing this is needed.

**Comment by ohmyarch** [comment]
I'm looking for a crate for scheduling tasks. I found that this crate has better api and async support than others, but the pg feature is not optional, that's it.

**Comment by zupzup** [comment]
Do you mean for scheduling tasks on a single instance, without synchronization?

So basically, it would remember previous runs in-memory somehow.

I can see that being useful, in general. But the primary use-case of this library is to handle multi-instance job runs with synchronization.

I also currently don't have much time to work on this, so maybe for your use-case it would make sense to look at the code (especially in `lib.rs`, and see if you can't build a very simple version of what you need based on that

**Comment by ohmyarch** [comment]
OK, thanks.

**Comment by alanhe** [comment]
I've similar needs. I want to run woddle within a single instance deployment and I don't have a DB.

I'm glad to find this.

What a great work to implement a cron scheduler in just 200+ lines of code!

**Comment by zupzup** [comment]
hey @alanhe 

Glad you like the library!

If you're only trying to schedule some functionality in an interval, you could look at https://docs.rs/tokio/1.1.1/tokio/time/struct.Interval.html

Otherwise, if you really need cron, using the cron-crate used in this library (https://github.com/zslayton/cron) together with tokio, you should be able to implement a very minimal version of what you need.

Something like this as a basic loop:

```rust
        let mut job_interval = tokio::time::interval(std::time::Duration::from_secs(5)); // check every 5 seconds if a job is ready to run
        loop {
            job_interval.tick().await;
            // check if your job is ready to run based on the cron expression - (maybe look at is_ready_to_run within db.rs of woddle for help)
        }
```

Providing a non-db version of woddle is, as mentioned above, not really in scope right now, since the synchronization is a crucial part.
